services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: global-finance-db
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_DB=global_finance_db'
      - 'POSTGRES_PASSWORD=admin123'
      - 'POSTGRES_USER=user'
    volumes:
      - 'postgres_data_new:/var/lib/postgresql/data'
    restart: always

volumes:
  postgres_data_new: