spring:
  application:
    name: global-finance-api
  
  # DATABASE CONFIGURATION
  datasource:
    url: jdbc:postgresql://localhost:5433/global_finance_db
    username: user
    password: admin123
    driver-class-name: org.postgresql.Driver

  # JPA CONFIGURATION (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update  # CREATE AUTO TABLES
    show-sql: true      # SHOW SQL QUERIES
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day in ms